### ISSUE TITLE
some pyrogram sessions

### ISSUE THREAD

**Issue by mmdy6628** [SpaceLabLTD/session-conv-bot#1]
Hello . Thank you very much for this robot
Sorry, for some pyrogram sessions the program gives an error that the session could not be loaded. I checked the code and came to the conclusion that it is self._date not defines and this session has taken 7 values instead of 6 in the sqlite table that named sessions.
What is the problem?

**Comment by HasibulKabir** [comment]
It has been fixed. Pyrogram session v2 has 6 columns and in v3 it is 7. Now it has been fixed with Aiogram implementation in bot,

**Comment by Softexdigitalbd** [comment]
> It has been fixed. Pyrogram session v2 has 6 columns and in v3 it is 7. Now it has been fixed with Aiogram implementation in bot,

how to use this can you please help me i have pyrogram .session file now i need to convert in to telethon .session file how can i do that . Where to put pyrogram exixting session file to convert
